Adding ansible.md to repo
coopdevs/handbook pull request #4
Opened 2020-01-15 11:00 UTC by mperezv

Adding ansible.md to repo.

2020-01-15 12:16 UTC, raneq requested changes
Este artículo faltaba mucho! Me gusta este estilo sintético y estructurado.
Te he dejado algunos comentarios para complementar el contenido. Mira si tienen sentido para ti y si quieres añadir o cambiar algo, por favor.

2020-01-15 12:16 UTC, raneq commented on ansible.md
> +Ansible está organizado en módulos que son las unidades de código que ejecuta. Se puede invocar un solo módulo con una *task* o varios diferentes en un *playbook*. Existen módulos predefinidos que An
Cuando dices que se puede invocar un solo módulo, te refieres a `ansible -m <module-name>` ?
Como dices más abajo, los playbooks contienen tasks, por eso creo que es mejor separar "1 solo módulo -> cli" y "varios módulos -> playbooks y tasks"

2020-01-15 12:16 UTC, raneq commented on ansible.md
> +Los roles son grupos de ficheros y *tasks* definidos sobre un grupo de *hosts* y basados en una estructura de ficheros concreta. Existen roles de Ansible y roles que aporta la comunidad en [galaxy](h
En nuestros roles, el grueso del desarrollo está en las `tasks`, `defaults` y `templates`. Los roles también hay `files`, `handlers`, `vars` y `meta`. Creo que es tan importante decir que hay tareas como variables y templates.

2020-01-15 12:16 UTC, raneq commented on ansible.md
> +Los roles son grupos de ficheros y *tasks* definidos sobre un grupo de *hosts* y basados en una estructura de ficheros concreta. Existen roles de Ansible y roles que aporta la comunidad en [galaxy](h
No entiendo bien lo de "definidos sobre un grupo de hosts". Los roles deberían ser independientes de los hosts, no sé si te refieres a eso.

2020-01-15 12:16 UTC, raneq commented on ansible.md
> +En Coopdevs usamos Ansible en nuestras instalaciones para asegurarnos de que los diferentes servidores que gestionamos están en el estado que queremos y, de esta manera, poder mantener nuestro softwa
También para :
1. acortar el tiempo de deploy (despliegue?) de nuevas máquinas y de recuperación en caso de fallos graves.
2. facilitar la creación de entornos de trabajo paralelos: desarrollo, pruebas y producción

2020-01-16 09:05 UTC, mperezv commented on ansible.md
> +En Coopdevs usamos Ansible en nuestras instalaciones para asegurarnos de que los diferentes servidores que gestionamos están en el estado que queremos y, de esta manera, poder mantener nuestro softwa
Pues me da la sensación de que tienes razón en todos tus comentarios, ahora le hago un lavado de cara. Gracias!

2020-01-17 11:00 UTC, closed without merging