Add ansible.md
coopdevs/handbook pull request #5
Opened 2020-01-16 12:07 UTC by mperezv

Second version of ansible.md

2020-01-16 15:18 UTC, sauloperez approved these changes

2020-01-16 15:19 UTC, sauloperez commented
What happens then with https://github.com/coopdevs/handbook/pull/4 ? Does this one contain those changes?

2020-01-17 09:02 UTC, mperezv commented
@sauloperez It should, if I did everything right.

2020-01-17 15:59 UTC, danypr92 requested changes

2020-01-17 15:59 UTC, danypr92 commented on devenv.md
> +# devenv
What do you think about to move this file to another MR? One for the devenv documentation.

2020-01-17 15:59 UTC, danypr92 commented on ansible.md
> +Ansible está organizado en módulos que son las unidades de código que ejecuta. Se puede invocar un solo módulo con `ansible -m <module-name> o varios diferentes en un *playbook*. Existen módulos pred
```suggestion
Ansible está organizado en módulos que son las unidades de código que ejecuta. Se puede invocar un solo módulo con `ansible -m <module-name>` o varios diferentes en un *playbook*. Existen módulos predefinidos que Ansible facilita, pero también se pueden crear propios.
```

2020-01-17 15:59 UTC, danypr92 commented on ansible.md
> +Se definen en Tasks/main.yml dentro de la carpeta de cada rol.
```suggestion
Se definen en `tasks/main.yml` dentro de la carpeta de cada rol.
```

2020-01-21 12:09 UTC, mperezv commented
Finally, we decided to add it to our wiki [here](https://github.com/coopdevs/handbook/wiki/Uso-de-Ansible-en-Coopdevs).

2020-01-21 12:09 UTC, closed without merging